llvm/Dockerfile
llvm/clang_wrap.sh

llvm: new version based on sid

---

golang/wasi/Dockerfile
golang/wasi/README.md
golang/wrapper.sh

golang: add wasi variant

---

.github/workflows/golang.yml
golang/Dockerfile
golang/Dockerfile.test
golang/wrapper.sh

* Fix GOBIN unset parameter (ref. #6)
* Add a simple [GitHub Action test workflow](https://github.com/crazy-max/xx/runs/744505240?check_suite_focus=true) to avoid regressions

Fix GOBIN unset parameter

---

.github/workflows/golang.yml

Closes #10 
Add `publish` job to push image to DockerHub.
* On `push tag` like `v1.2.3` will create `golang-1.2.3`, `golang` docker tags and push to DockerHub
* On `push` will create `golang-<branch>` docker tag and push to DockerHub
* On `pull_request` will only build locally
@tonistiigi You will need to create secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.

Publish to DockerHub through GitHub Actions

---

golang/wrapper.sh

Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>

add support for mips64le

---

.github/workflows/build.yml
docker-bake.hcl

github: run tests with image matrix

---

README.md

readme: fix wrong flag in example

---

.github/workflows/build.yml

github: add testing for debian:bookworm

---

README.md
base/Dockerfile
base/xx-apt

xx-apt: allow calling with xx-apt-get alias

---

base/test-info-alpine.bats
base/test-info-debian.bats
base/xx-info

add xx-info sysroot

---

base/test-clang.bats
base/xx-cc

xx-cc: set rpath-link on ld linker

---

.github/workflows/build.yml
base/Dockerfile

github: run tests against alpine 3.15

---

base/xx-info

info: use case for long if statements

---

README.md

readme: updates for 1.1

---

base/test-info-alpine.bats
base/test-info-debian.bats
base/test-info-rhel.bats
base/xx-info

xx-info: fix variant

---

base/test-go.bats
base/test-info-alpine.bats
base/test-info-common.bats
base/test-info-debian.bats
base/test-info-rhel.bats
base/xx-go
base/xx-info
docker-bake.hcl

support for `xx-info`, `xx-go` for now.

handle mips arch

---

base/xx-cc

In an adventure to cross-compile python these have popped seem to make sense for this projects goals.
If they should go elsewhere please let me know.

xx-cc: add additional llvm-profdata and readelf

---

base/xx-info

xx-info: fix os-version

---

.github/workflows/build.yml
README.md
base/Dockerfile
base/fixtures/hello_cargo/Cargo.toml
base/fixtures/hello_cargo/src/main.rs
base/test-cargo.bats
base/test-info-alpine.bats
base/test-info-debian.bats
base/xx-cargo
base/xx-info

follow-up https://github.com/tonistiigi/xx/pull/27
fixes #79
fixes #80 
fixes #81

xx-cargo: add tests and docs

---

MAINTAINERS

add maintainers file

---

.github/workflows/build.yml

ci: bump actions

---

.github/workflows/build.yml

ci: os update

---

base/xx-cargo

xx-cargo: set PKG_CONFIG

---

README.md
src/test-verify.bats
src/xx-verify

fixes #98
follow-up
* https://github.com/moby/moby/pull/44513#discussion_r1049661250
* https://github.com/moby/buildkit/pull/3994#discussion_r1255020450

xx-verify: XX_VERIFY_STATIC env

---

.github/workflows/bats-assert.yml
.github/workflows/ld.yml
.github/workflows/llvm.yml
.github/workflows/sdk-extras.yml
docker-bake.hcl

follow-up https://github.com/tonistiigi/xx/pull/119

ld: fix missing platforms

---

docker-bake.hcl

~Also switch to a [`matrix`](https://docs.docker.com/build/bake/reference/#targetmatrix) to set tests.~

test: don't export build result

---

util/bats-assert/Dockerfile
util/bats-assert/test.bats.golden

Hopefully adding the alpine version makes it more stable.

bats: fix bats test update
