golang/wrapper.sh

This PR allows to add binaries location to PATH when cross-compiling.
For example if we use `go install ./...` binaries will be located to a specific folder regarding it's cross-compilation.
`GOOS=darwin GOARCH=amd64 go install ./...` will go to `$GOPATH/bin/$GOOS_$GOARCH` or not depending of the `$BUILDPLATFORM`.
This is the case for [this Dockerfile](https://github.com/crazy-max/AdGuardHome/blob/master/Dockerfile#L34) where [we use `packr` tool](https://github.com/crazy-max/AdGuardHome/blob/master/main.go#L1-L3) through go generate.

Add binaries location to PATH when cross-compiling

---

golang/wrapper.sh

I tried to use this Docker image to cross compile [go-face](https://github.com/Kagami/go-face).
But I ran into troubles as the library depends on C++ code, and the cross compiler wasn't used as the `CXX` environment variable wan't set. Adding this made it work.

Add C++ cross compilers to golang wrapper.h

---

base/xx-cc

This didn't show up before shellcheck was added https://github.com/tonistiigi/xx/commit/41f7f39551857836e691da81580296ba5acf6ac3#diff-36944549da6de5003f30429e7f2bc5277ae26d2bbd5ed042661450eef351aacdR326

fix checksum validation

---

base/test-clang.bats
base/test-go.bats
base/test_helper.bash
base/xx-apk
base/xx-apt
base/xx-cc
base/xx-info

enable experimental riscv64 support

---

base/xx-cc

`XX_CC_PREFER_LINKER=ld` currently always forced a download. That download would fail if `ld` already existed in system. One such case was where on amd64 systems the native `ld` can also link `386`.

don't download ld if preferred but already in the system

---

base/xx-cc

Make sure to use GNU Wget and not the buysbox one because Busybox's wget stopped when it couldn't reach the IPv6 destination. Standard wget, instead, falls back to the IPv4 address, completing the download.
If `wget --version` is ok that's the GNU one, otherwise fails with `wget: unrecognized option: version` on busybox. Maybe we could use a better check.
```shell
docker buildx build --load -<<EOF
FROM golang:1.17.0-alpine AS build
RUN (wget --version || true) && which wget
RUN apk add wget
RUN wget --version && which wget
EOF
```
```
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 167B done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s
#3 [internal] load metadata for docker.io/library/golang:1.17.0-alpine
#3 …
```

Install GNU wget if it fails

---

base/xx-verify

Currently, xx-verify doesn't support FreeBSD targets.
This change re-uses Linux logic for FreeBSD. It is possible, because
FreeBSD uses ELF executable format and `file` utility works exactly
the same on both platforms.

xx-verify: Add FreeBSD

---

base/test-go.bats
base/test_helper.bash
base/xx-cc
base/xx-go
base/xx-verify
base/xx-windres

debian has decided to remove it and break the world.
https://salsa.debian.org/debian/debianutils/-/commit/3a8dd10b4502f7bae8fc6973c13ce23fc9da7efb
This should make `debian:sid` green again.

remove usage of which

---

base/test-verify.bats
base/xx-verify

Some versions of `file` return this for static+pie.
Overall, I think we should switch to `readelf` from `file` for this but I need to do some reading on what is the most reliable way. @tiborvass I think you looked into this some time ago?

xx-verify: allow static-pie for static check

---

base/test-apt.bats
base/xx-apt

`apt-get info` does not exist and `apt info` is missing in ubuntu 18.04

apt: fix package check

---

.github/workflows/build.yml
README.md
base/Dockerfile
base/test-info-rhel.bats
base/xx-info
docker-bake.hcl

Handle RHEL based distrib for `xx-info`. This is partially needed for https://github.com/docker/buildx/pull/840 to handle RPM arch package properly. Following distribs are currently handled:
```
$ docker run --rm -it fedora:35 cat /etc/os-release
NAME="Fedora Linux"
VERSION="35 (Container Image)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora" …
```

xx-info: handle rhel arch

---

.github/workflows/build.yml
base/Dockerfile
base/test-info-rhel.bats
base/xx-info

follow-up #52 with oracle linux support that was missing
second commit add tests against currently supported rhel distribs (just xx-info test atm)

xx-info: oracle linux support

---

base/xx-apk

Enables `--rtlib=compiler-rt` instead of installing `gcc` for libgcc libs.
Not sure how to achieve similar for debian/ubuntu atm. The files exist in `libclang-common-dev` but library can't be installed at the same time as `clang`. Possibly only solution is to revive our own build https://github.com/tonistiigi/xx/blob/b7c9c0be7c06c901d84e223382b4e460a1f20fec/base/Dockerfile#L345 .
We could also extend `xx-clang` to detect when compiler-rt is installed and default `--rtlib`.

xx-apk: add rules for compiler-rt

---

.github/workflows/build.yml

encounter the following issue in #64: https://github.com/tonistiigi/xx/runs/6196721054?check_suite_focus=true#step:3:238
```
#0 1.003 + . /etc/os-release
#0 1.004 + '[' centos '!=' fedora ']'
#0 1.004 + yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
#0 1.454 CentOS Linux 8 - AppStream                      232  B/s |  38  B     00:00    
#0 1.458 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
the current official Docker image `centos:8` is a CentOS 8 that is EOL since December 2021 and epel release repo now uses CentOS Stream 8 which is not compatible.
I don't see any CentOS Stream 8 official image atm so switch to CentOS 7 (maintained until 2024) in our ci matrix.
Signed-off-by: …

ci: centos 8 eol, use centos 7 instead

---

base/test-clang.bats

follow-up https://github.com/tonistiigi/xx/pull/65#issuecomment-1111184217
looks like since bookworm `command` requires file to have execute permission.
test fails here https://github.com/tonistiigi/xx/blob/6bf9570dbd748abf5ed47c6366ce4828da258912/base/test-clang.bats#L174 because `command` not valid in https://github.com/tonistiigi/xx/blob/6bf9570dbd748abf5ed47c6366ce4828da258912/base/xx-cc#L454

test-clang: chmod missing

---

base/xx-info

- relates to https://github.com/docker/docker-ce-packaging/pull/713
macOS doesn't have a /etc/os-release, which caused the script to fail
when running on the host.
Also adds detection if /etc/os-release exists,.

base: fix xx-info failing on macOS

---

.github/workflows/build.yml
base/Dockerfile
docker-bake.hcl

* `alpine 3.16`
* `fedora 36`
* `ubuntu 22.04`
removes `ubuntu 21.10` (eol since July 14, 2022) that fails in our pipeline: https://github.com/tonistiigi/xx/runs/7837299244?check_suite_focus=true#step:3:242
```
> [test-base-debian 2/3] RUN --mount=type=cache,target=/pkg-cache     rm -rf /var/cache/apt/archives &&     ln -s /pkg-cache /var/cache/apt/archives &&     rm /etc/apt/apt.conf.d/docker-clean &&     echo 'Binary::apt::APT::Keep-Downloaded-Packages "1";' > /etc/apt/apt.conf.d/keep-downloads &&     apt update && apt install --no-install-recommends -y bats vim:
#19 0.696   404  Not Found [IP: 185.125.190.36 80]
#19 0.771 Err:7 http://archive.ubuntu.com/ubuntu impish-updates Release
#19 0.771   404  Not Found [IP: 185.125.190.36 80]
#19 0.847 Err:8 http://archive.ubuntu.com/ubuntu …
```

ci: os update

---

base/test-info-common.bats
base/xx-info

I'm working on `xx-yum` and `xx-dnf` but needs first a way to print os version so I can manage some corner cases when fetching packages.

xx-info: os-version

---

base/test-info-alpine.bats
base/test-info-debian.bats
base/xx-apk
base/xx-cargo
base/xx-cc
base/xx-info

Allow building rust projects. Support installing rust via `rustup` (alpine/debian) and alpine packages (rust/rust-stdlib). Haven't tested official image. Debian package-based installs will probably not be supported as packages don't seem to be properly separated.
Currently have tested with these Dockerfile stages:
```
ARG RUST_ALG=alpine-rustup
FROM --platform=$BUILDPLATFORM alpine AS rust-alpine-rustup
COPY --from=xx / /
RUN apk add clang lld musl-dev gcc git curl
WORKDIR /work
RUN curl -O https://static.rust-lang.org/rustup/archive/1.24.3/$(XX_VENDOR=unknown xx-info)/rustup-init && \
chmod +x rustup-init && \
./rustup-init -y --no-modify-path --profile=minimal
ENV PATH=/root/.cargo/bin:$PATH
RUN git clone git://github.com/BLAKE3-team/BLAKE3.git
WORKDIR BLAKE3/b3sum
RUN cargo fetch
ARG …
```

Rust support

---

base/test-apk.bats
base/test-apt.bats
base/xx-apt

xx-apt: fix xx essentials

---

README.md
base/test-cargo.bats
base/xx-cargo

xx-cargo: rename to --print-target-triple

---

.github/workflows/build.yml

Needs to allow failure for test on bookworm while waiting for https://github.com/tonistiigi/xx/issues/95 to be fixed, otherwise we can't do a release.

ci: allow failure for bookworm

---

base/xx-cc

follow-up https://github.com/moby/buildkit/issues/3625#issuecomment-1427088968
Use prebuilt ld built from https://github.com/crazy-max/xx/actions/runs/4157262742 and published in https://github.com/tonistiigi/xx/releases/tag/prebuilt%2Fld-2.38-0 while waiting for https://github.com/tonistiigi/xx/pull/68 and https://github.com/tonistiigi/xx/pull/101

xx-cc: update prebuilt ld to binutils 2.38

---

.github/workflows/build.yml
docker-bake.hcl

Saw this after merging https://github.com/tonistiigi/xx/pull/103: https://github.com/tonistiigi/xx/actions/runs/5521258598/jobs/10069278303#step:7:120
```
/usr/bin/docker buildx bake --file ./docker-bake.hcl --file /tmp/docker-actions-toolkit-681WDL/docker-metadata-action-bake.json --metadata-file /tmp/docker-build-push-RnQdwz/metadata-file --push base-all --print
ERROR: failed to find target base-all
Error: The process '/usr/bin/docker' failed with exit code 1
```
Looks like an oversight.
___
`TEST_BASE_TYPE` was also not set in the workflow.

fix bake definition

---

.github/workflows/build.yml
src/test-go.bats

fixes #95 
Since bookworm, `pkgconf` is installed. Before bookworm, crosswrapper scripts were created by a dpkg trigger when `xx-c-essentials` was installed, such as bullseye:
```
$ TARGETARCH=arm64 xx-apt install xx-c-essentials
...
$ ls -al /usr/bin/*pkg-config
lrwxrwxrwx 1 root root    34 Jul 10 08:57 /usr/bin/aarch64-linux-gnu-pkg-config -> /usr/share/pkg-config-crosswrapper
-rwxr-xr-x 2 root root 48000 Apr 21  2020 /usr/bin/aarch64-unknown-linux-gnu-pkg-config
-rwxr-xr-x 2 root root 48000 Apr 21  2020 /usr/bin/pkg-config
lrwxrwxrwx 1 root root    34 Jul 10 08:56 /usr/bin/x86_64-linux-gnu-pkg-config -> /usr/share/pkg-config-crosswrapper
```
Since bookworm this is not the case anymore:
```
$ TARGETARCH=arm64 xx-apt install xx-c-essentials
...
$ ls -al /usr/bin/*pkg-config
lrwxrwxrwx 1 …
```

golang: fix test with pkgconf

---

src/test-cargo.bats

`386-hellocargo-rustup` in alpine 3.13 and 3.14 since rust 0.71.0: https://github.com/tonistiigi/xx/actions/runs/5560116409/jobs/10156856888#step:5:576
Pin rust version to 1.69.0 to fix the test.

test: pin rust version with rustup

---

docker-bake.hcl
src/ld/Dockerfile

Now that ld is being built on ci since #114, we can be aligned with what we currently ship in https://github.com/tonistiigi/xx/releases/tag/prebuilt%2Fld-2.38-0 related to https://github.com/tonistiigi/xx/pull/102

Update binutils for prebuilt ld to 2.38

---

util/bats-assert/Dockerfile
util/bats-assert/test.bats.golden

Github has deprecated git protocol

bats: update git URLs

---

docker-bake.hcl

Bug introduced in https://github.com/tonistiigi/xx/pull/103
With follow-up PR https://github.com/tonistiigi/xx/pull/113 to fix the issue
but didn't fix the default target

fix default bake target

---

docker-bake.hcl
hack/dev-shell
src/Dockerfile

Fixes the dev-shell support that looks broken after the source migration to `/src`.
Supports:
```
./hack/dev-shell
TEST_BASE_TYPE=debian ./hack/dev-shell
TEST_BASE_TYPE=debian TEST_BASE_IMAGE=debian:sid ./hack/dev-shell
DEV_SDK_PLATFORM=darwin/arm64 ./hack/dev-shell
```

hack: fix dev-shell script

---

src/xx-apk

Starting from Alpine 3.18, `compiler-rt` install on `usr/lib/llvm*` instead of `usr/lib/clang`. ([Package contents of 3.17](https://pkgs.alpinelinux.org/contents?file=&path=&name=compiler-rt&branch=v3.17&repo=main&arch=aarch64), [3.18](https://pkgs.alpinelinux.org/contents?file=&path=&name=compiler-rt&branch=v3.18&repo=main&arch=aarch64)) So xx-apk failed to create symlinks with error message below.
```
/opt/app # set -ex
/opt/app # xx-apk add compiler-rt
+ xx-apk add compiler-rt
+ apk  --root /aarch64-alpine-linux-musl add compiler-rt
OK: 55 MiB in 7 packages
find: /aarch64-alpine-linux-musl/usr/lib/clang: No such file or directory
```
Here is sample output of `apk info -qL compiler-rt`
```
/ # apk info -qL compiler-rt
usr/lib/clang/15.0.7/bin/hwasan_symbolize …
```

fix: xx-apk failed to symlink compiler-rt on Alpine 3.18

---

README.md
docker-bake.hcl
src/Dockerfile
src/test-apt.bats
src/xx-apt

related to https://github.com/moby/moby/pull/44735#issuecomment-1866355689
needs #133 
Since Ubuntu Noble 24.04 and Debian Bookworm, `/etc/apt/sources.list` has moved to `/etc/apt/sources.list.d/ubuntu.sources` and `/etc/apt/sources.list.d/debian.sources` respectively.
They also use the new deb822 format: https://repolib.readthedocs.io/en/latest/deb822-format.html
```
docker run --rm -it debian:12 cat /etc/apt/sources.list.d/debian.sources
Types: deb
URIs: http://deb.debian.org/debian
Suites: bookworm bookworm-updates
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
Types: deb
URIs: http://deb.debian.org/debian-security
Suites: bookworm-security
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
```

debian/ubuntu: fix apt sources list location

---

.github/dependabot.yml
.github/workflows/bats-assert.yml
.github/workflows/build.yml
.github/workflows/ld.yml
.github/workflows/llvm.yml
.github/workflows/sdk-extras.yml

Also adds dependabot to keep gha up to date

ci: update github actions to latest stable

---

README.md
hack/generate-ld-shas

with handling of provenance introduced in https://github.com/tonistiigi/xx/pull/141/commits/419673703f90a6495fef15bd2c97498886685e85 we need to only iterate on tarballs when generating `xx-ld-shas`.

ld: fix xx-ld-shas generation

---

src/xx-apt

Fixes setting arch for new format

fix: add support for deb822 sources.list format

---

src/Dockerfile

related to https://github.com/tonistiigi/xx/pull/157#issuecomment-2133388590
https://github.com/tonistiigi/xx/actions/runs/9254378665/job/25456054906?pr=157#step:6:289
```
0.059 + yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
0.060 /bin/sh: line 5: yum: command not found
```

dockerfile: fix test-base-rhel

---

src/Dockerfile

relates to https://github.com/tonistiigi/xx/actions/runs/10112723728/job/27985481000#step:6:423
```
#21 1.333 + yum update -y
#21 1.426 Loaded plugins: fastestmirror, ovl
#21 1.469 Loading mirror speeds from cached hostfile
#21 1.530 Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
#21 1.530 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```
CentOS 7 has reached EOL on June 30: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7. Switch to vault repo.

dockerfile: switch to vault repo for centos 7

---

src/xx-apk
src/xx-apt
src/xx-cargo
src/xx-cc
src/xx-verify

relates to https://github.com/tonistiigi/xx/actions/runs/10355410498/job/28662989273#step:5:784
```
> [test-apk test-apk 2/2] RUN --mount=type=cache,target=/pkg-cache,sharing=locked [ ! -f /etc/alpine-release ] || ./test-apk.bats:
0.515 not ok 5 skip-nolinux
0.517 # (from function `assert_success' in file bats-assert/src/assert.bash, line 114,
0.517 #  in test file test-apk.bats, line 54)
0.519 #   `assert_success' failed
0.520 #
0.520 # -- command failed --
0.520 # status : 1
0.520 # output : /usr/bin/xx-apk: line 7: can't create /var/lock/xx-apk: nonexistent directory
0.520 # --
0.520 #
```
Alpine edge has `/var/lock` as symlink to `/run/lock` but this dir doesn't exist:
```
$ docker run --rm -it alpine:edge sh -xc "ls -al /var/ && ls -al /run"
+ ls -al /var/
total 44
drwxr-xr-x   11 …
```

ensure /var/lock dir exists

---

.github/workflows/build.yml

relates to https://github.com/tonistiigi/xx/actions/runs/12239168823/job/34138978886#step:5:634
```
#49 0.065 
#49 0.065 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#49 0.065 
#49 0.139 Ign:1 http://security.ubuntu.com/ubuntu lunar-security InRelease
#49 0.166 Err:2 http://security.ubuntu.com/ubuntu lunar-security Release
#49 0.166   404  Not Found [IP: 91.189.91.82 80]
#49 0.294 Ign:3 http://archive.ubuntu.com/ubuntu lunar InRelease
#49 0.385 Ign:4 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
#49 0.476 Ign:5 http://archive.ubuntu.com/ubuntu lunar-backports InRelease
#49 0.568 Err:6 http://archive.ubuntu.com/ubuntu lunar Release
#49 0.568   404  Not Found [IP: 185.125.190.82 80]
#49 0.659 Err:7 http://archive.ubuntu.com/ubuntu lunar-updates …
```

ci: ubuntu 23.04 eol

---

src/test-go.bats
src/test_helper.bash

test: skip mips go build on ubuntu 22.04

---

src/Dockerfile

closes #179 
closes #178
follow-up https://github.com/tonistiigi/xx/pull/179#issuecomment-2528188582
`setup_file` and `teardown_file` are available since bats 1.2.1 but Ubuntu 20.04 currently ships Bats 1.2.0-dev. Let's install a stable release of bats.

dockerfile: install bats from source

---

.github/workflows/build.yml

relates to: https://github.com/tonistiigi/xx/actions/runs/12241031255/job/34145224508#step:5:962
```
#88 120.2 not ok 6 ppc64le-hellocargo-rustup
#88 120.2 # (from function `assert_success' in file bats-assert/src/assert.bash, line 114,
#88 120.2 #  from function `testHelloCargo' in file test-cargo.bats, line 30,
#88 120.2 #  from function `testHelloCargoRustup' in file test-cargo.bats, line 44,
#88 120.2 #  in test file test-cargo.bats, line 83)
#88 120.3 #   `testHelloCargoRustup' failed
#88 120.3 #
#88 120.3 # -- command failed --
#88 120.3 # status : 100
#88 120.3 # output (19 lines):
#88 120.3 #   + apt  install -y --no-install-recommends libc6-dev:ppc64el libgcc-10-dev:ppc64el
#88 120.3 #
#88 120.3 #   WARNING: apt does not have a stable CLI interface. Use with caution in scripts. …
```

ci: allow failure for bullseye-backports

---

src/test-go.bats

* needs #180
* relates to #177 
https://github.com/tonistiigi/xx/actions/runs/12236180951/job/34129079148#step:5:1002
```
#83 77.99 1..49
#83 89.73 # go version go1.18.1 linux/amd64
#83 89.73 ok 1 version
```

test-go: print version

---

src/xx-apk

`xx-apk` can return `0.069 mkdir: can't create directory '': No such file or directory` in latest alpine 3.21 https://github.com/tonistiigi/xx/blob/b0cde9e3c6120fc0b4b118bdd463ced0feb04070/src/xx-apk#L7 because `readlink -f` does not return a valid path. This seems to depend on the working directory. I don't see such behavior in `coreutils` and `man readlink` also does not suggest this as a valid behavior afaics.
As a workaround, temporarily switch the working directory to root before calling `readlink`.

xx-apk: fix problem with writing lock in latest alpine

---

src/xx-apk
src/xx-apt
src/xx-cargo
src/xx-cc
src/xx-verify

follow-up https://github.com/tonistiigi/xx/pull/185

fix with writing lock follow-ups

---

.github/workflows/.test.yml
.github/workflows/build.yml

Will make it easier to find out what fails:
And also improve build time:
Before:
Now:

ci: split tests in a reusable workflow

---

src/xx-apk

relates to https://github.com/tonistiigi/xx/actions/runs/12260586308/job/34205579093#step:5:879
```
> [test-clang test-clang 2/2] RUN --mount=type=cache,target=/pkg-cache,sharing=locked ./test-clang.bats:
43.15 #  in test file test-clang.bats, line 313)
43.15 #   `testHelloCPPLLD' failed
43.15 # rm: can't remove '/etc/llvm/xx-default.cfg': No such file or directory
43.15 # rm: can't remove '/usr/bin/*-apple-*-clang': No such file or directory
43.16 # rm: can't remove '/usr/bin/*-apple-*-clang++': No such file or directory
43.16 # mkdir: can't create directory '/loongarch64-alpine-linux-musl/etc/apk/keys': File exists
44.19 ok 23 386-c++-lld
45.49 ok 24 darwin-setup
```

xx-apk: fix mkdir

---

src/test-clang.bats

relates to https://github.com/tonistiigi/xx/actions/runs/12260586308/job/34205579093#step:5:879
```
> [test-clang test-clang 2/2] RUN --mount=type=cache,target=/pkg-cache,sharing=locked ./test-clang.bats:
43.15 #  in test file test-clang.bats, line 313)
43.15 #   `testHelloCPPLLD' failed
43.15 # rm: can't remove '/etc/llvm/xx-default.cfg': No such file or directory
43.15 # rm: can't remove '/usr/bin/*-apple-*-clang': No such file or directory
43.16 # rm: can't remove '/usr/bin/*-apple-*-clang++': No such file or directory
```

test(clang): suppress error message on clean

---

.github/workflows/build.yml

repo is archived https://archive.debian.org/debian/dists/bullseye-backports/
```
#21 [test-base-debian 2/3] RUN --mount=type=cache,target=/pkg-cache     rm -rf /var/cache/apt/archives &&     ln -s /pkg-cache /var/cache/apt/archives &&     rm /etc/apt/apt.conf.d/docker-clean &&     echo 'Binary::apt::APT::Keep-Downloaded-Packages "1";' > /etc/apt/apt.conf.d/keep-downloads &&     apt update && apt install --no-install-recommends -y bash vim
#21 0.127 
#21 0.127 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#21 0.127 
#21 0.209 Get:1 http://deb.debian.org/debian bullseye InRelease [75.1 kB]
#21 0.217 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [27.2 kB]
#21 0.217 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.0 …
```

ci: remove bullseye-backports
